# Book settings
title: Sudan Economic Monitoring
author: Data Lab
logo: docs/images/logo.png
only_build_toc_files: false

repository:
  url: https://github.com/worldbank/sudan-poverty-monitoring
  branch: main

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar: false
  extra_navbar: |
  <nav>
      <a href="index.html">Home</a> |
      <a href="nighttime_lights_iran.html">Nighttime Lights in Sudan</a> |
    </nav>
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: "/sudan-poverty-monitoring/"  # Use relative URL for GitHub Pages compatibility"
  extra_footer: |
    <div>
     Country borders or names do not necessarily reflect the World Bank Group’s official position. All maps are for illustrative purposes and do not imply the expression of any opinion on the part of the World Bank, concerning the legal status of any country or territory or concerning the delimitation of frontiers or boundaries
    </div>
    <div>
        <b>All content (unless otherwise specified) is subject to the <a href="https://www.mozilla.org/en-US/MPL">Mozilla Public License.</a></b>
    </div>
  favicon: docs/images/favicon.ico

#######################################################################################
# Execution settings
execute:
  execute_notebooks: off

#######################################################################################
# Bibliography settings
bibtex_bibfiles:
  - docs/bibliography.bib

#######################################################################################
# Sphinx settings
sphinx:
  config:
    html_show_copyright: false
    html_last_updated_fmt: "%b %d, %Y"
